
koji-db:
    image: "postgres:9.4"
    hostname: koji-db
    environment:
        - POSTGRES_DB=koji
        - POSTGRES_USER=koji
        - POSTGRES_PASSWORD=mypassword

koji-hub:
    build: hub
    hostname: koji-hub
    volumes:
        - /opt/koji:/opt/koji:rw,z
        - /opt/koji-clients:/opt/koji-clients:rw,z
        - /mnt/koji:/mnt/koji:rw,z
    links:
        - koji-db
    ports:
        - "80:80"


koji-client:
    build: client
    hostname: koji-client
    volumes_from:
        - koji-hub:rw
    links:
        - koji-hub

